on: pull_request

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const diff_url = context.payload.pull_request.diff_url
            const result = await github.request(diff_url)
            if(result.data.includes('.gitignore')) {
              await github.rest.issues.createComment({
              
              body: 'You are not authorized to make changes in .gitignore file!'
            })
              throw new Error('You are not authorized to make changes in .gitignore file!')
            }