on: pull_request

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const diff_url = context.payload.pull_request.diff_url
            const result = await github.request(diff_url)
            if(context.payload.sender.login !== 'abhay-singh-au3' && context.payload.sender.login !== 'vasani-arpit') {
              if(result.data.includes('.gitignore')) {
                await github.rest.issues.createComment({
                  issue_number: context.issue.number,
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  body: 'You are not authorized to make changes in .gitignore file!'
                })
                throw new Error('You are not authorized to make changes in .gitignore file!')
              }
            }      
      - uses: actions/github-script@v6
        with:
          script: |
            const diff_url = context.payload.pull_request.diff_url
            const result = await github.request(diff_url)
            if(context.payload.sender.login !== 'abhay-singh-au3' && context.payload.sender.login !== 'vasani-arpit') {
              if(!context.payload.pull_request.comments) {
                throw new Error('You have not added a decription in the PR! Please add a description.')
              }
            }
      - uses: actions/github-script@v6
        with:
          script: |
            - uses: actions/github-script@v6
        with:
          script: |
            const diff_url = context.payload.pull_request.diff_url
            const result = await github.request(diff_url)
            console.log("STEP 4", github.rest.issues)
            const comments = await github.rest.issues.commets({
                    issue_number: context.issue.number,
                    owner: context.repo.owner,
                    repo: context.repo.repo
                  })
            console.log("COMMETS====>",comments)
      - uses: actions/github-script@v6
        with:
          script: |
            const diff_url = context.payload.pull_request.diff_url
            const result = await github.request(diff_url)
            console.log("RESULT DATA++>",result.data)
              if(result.data.includes('process.env')) {
                if(!result.data.includes('.env.sample')) {
                  throw new Error('You have used a enviroment variable but not updated the .env.sample file!')
                }
              }